### ISSUE TITLE
Update Makefile for tests to reflect the change in the structure of the master branch 

### ISSUE THREAD

**Issue by yjyun0922** [cmsc22000-project-2018/api#58]
the makefile doesn't build anymore because the path is different from the actual path due to the recent changes in the repository structure, so I'm going to try to make changes to the Makefile inside the tests folder to make it build again

**Comment by chen-alan** [comment]
[problematic Makefile](https://github.com/cmsc22000-project-2018/api/commit/85327f9dada85b35f6465ac34714bd1817736001#diff-b67911656ef5d18c4ae36cb6741b7965) was fixed with pull request #57
